"""student spec

Revision ID: 85b361f3538d
Revises: 4239e6082e39
Create Date: 2022-12-11 13:36:33.654145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b361f3538d'
down_revision = '4239e6082e39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('specialization', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'specialization')
    # ### end Alembic commands ###
