"""nullable fields

Revision ID: eb91e084ccbf
Revises: 598dac4289ae
Create Date: 2022-12-12 14:33:54.314595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb91e084ccbf'
down_revision = '598dac4289ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
